config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'pages#landing'
  get 'home', to: 'pages#home'

  resources :sports, only: [:index, :show, :new, :create]
  resources :routines, only: [:new, :create, :show, :destroy] do
    get 'routinestart', to: 'routines#routine_start'
  end
  resources :stretches, only: [:index, :show] do
    resources :routines, only: :update
    resources :stretches_routines, only: :create
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/routine.rb
class Routine < ApplicationRecord
  belongs_to :imageable, polymorphic: true
  has_many :stretches_routines, dependent: :destroy
  has_many :stretches, through: :stretches_routines
  has_one_attached :background
end

app/models/sport.rb
class Sport < ApplicationRecord
  has_many :routines, as: :imageable
end

app/models/stretch.rb
class Stretch < ApplicationRecord
  has_many :stretches_routines
  has_many :routines, through: :stretches_routines
end

app/models/stretches_routine.rb
class StretchesRoutine < ApplicationRecord
  belongs_to :routine
  belongs_to :stretch
end

app/models/user.rb
class User < ApplicationRecord
  has_many :sports
  has_many :routines, as: :imageable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # def default_url_options
  #   { host: ENV["DOMAIN"] || "localhost:3000" }
  # end
end

app/controllers/routines_controller.rb
class RoutinesController < ApplicationController
  def show
    @routine = Routine.find(params[:id])
    @stretches = @routine.stretches
    @photos
  end

  def new
    @newroutine = Routine.new
  end

  def create
    @newroutine = Routine.new(routines_params)
    @newroutine.imageable = current_user
    if @newroutine.save
      redirect_to home_path
    else
      render :new
    end
  end

  def routine_start
    @routine = Routine.find(params[:routine_id])
    @stretches = @routine.stretches
  end

  def destroy
    @routine = Routine.find(params[:id])
    @routine.destroy

    redirect_to home_path
  end

  private

  def routines_params
    params.require(:routine).permit(:name, :description, :background)
  end
end

app/controllers/sports_controller.rb
class SportsController < ApplicationController
  def index
    @sports = Sport.where(imageable_type: 'Sport')
    @myroutines = Sport.where(imageable: current_user.id)
  end

  def show
    @sport = Sport.find(params[:id])
    @routines = Routine.where(imageable_type: 'Sport').where(imageable_id: @sport.id)
  end

  def new
    @myroutine = Sport.new
  end

  def create
    @myroutine = Sport.new(sports_params)
    @myroutine.user = current_user
    if @myroutine.save
      redirect_to root_path
    else
      render :new
    end
  end

  private

  def sports_params
    params.require(:sport).permit(:name)
  end
end

app/controllers/stretches_controller.rb
class StretchesController < ApplicationController
  def index
    # raise
    if params[:query].present?
      sql_query = " \
        stretches.name @@ :query \
        OR stretches.difficulty @@ :query \
      "
      @stretches = Stretch.where(sql_query, query: "%#{params[:query]}%")
    else
      @stretches = Stretch.all
    end
  end

  def show
    @stretch = Stretch.find(params[:id])
    @new = StretchesRoutine.new
  end
end

app/controllers/stretches_routines_controller.rb
class StretchesRoutinesController < ApplicationController
  def create
    if current_user.routines.any?
      routine = Routine.find(params[:stretches_routine][:routine])
      stretch = Stretch.find(params[:stretch_id])
      combo = StretchesRoutine.new
      combo.routine = routine
      combo.stretch = stretch
      combo.save
      redirect_to stretches_path
    else
      redirect_to new_routine_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/routines_helper.rb
module RoutinesHelper
end

app/helpers/sports_helper.rb
module SportsHelper
end

app/helpers/stretches_helper.rb
module StretchesHelper
end

app/helpers/stretchesroutines_helper.rb
module StretchesroutinesHelper
end

app/views/routines/new.html.erb
<div class="text-center"><h1>create your new routine</h1></div>

<%= simple_form_for @newroutine do |f| %>
  <%= f.input :name %>
  <%= f.input :description %>
  <%= f.file_field :background, placeholder:"Routine picture URL *", label: false, class:"select-file"%>
  <%= f.submit 'submit', class: 'btn btn-primary' %>
<% end %>

app/views/routines/routine_start.html.erb
<% content_for :nonav, render('shared/nofoot') %>

<div class="car-container">
  <div class='container'>
  <div class='content-big' data-controller="routine-start" data-routine-start-count-value="<%= @stretches.count %>">
    <div class="base-timer" data-routine-start-target="counter">
      <svg class="base-timer__svg" viewBox="0 0 100 100" xmlns="http://www.w3.org/2000/svg">
        <g class="base-timer__circle">
          <circle class="base-timer__path-elapsed" cx="50" cy="50" r="45" />
          <path
            data-routine-start-target="color"
            id="base-timer-path-remaining"
            stroke-dasharray="283"
            class="base-timer__path-remaining blue"
            d="
              M 50, 50
              m -45, 0
              a 45,45 0 1,0 90,0
              a 45,45 0 1,0 -90,0
            "
          ></path>
        </g>
      </svg>
      <span data-routine-start-target="timer" class="base-timer__label">
        <!-- Remaining time label -->
      </span>
    </div>
    <div id="carouselExampleSlidesOnly" class="vertical carousel slide over-big" data-routine-start-target="carousel">
      <div class="carousel-inner">
        <div class="carousel-item active">
          <div class='card routine-start-head'>
            <h2 class='head-start' style='color: white; font-size: 46px;'>Are you <br><span style='color: #55A4BA'>ready?</span></h2>
          </div>
        </div>
        <% @stretches.each do |stretch| %>
          <div class='carousel-item'>
            <div class='routine-container-timer' data-routine-start-duration-value="<%= stretch.duration %>">
              <div class='container'>
                <div class='content'>
                  <img src= <%= stretch.photo %> class="stretch-img" alt="...">
                </div>
              </div>
            </div>
          </div>
        <% end %>
        <div class="carousel-item over-end">
          <div class='card routine-end-head'>
            <h2 style='color: white; font-size: 45px;'>Great job!</h2>
            <p style='color: #55A4BA; font-size: 28px;'>Rate this routine:</p>
            <br>
            <p style='color: white; font-size: 24px;'>Difficulty:</p>
            <fieldset class="form-group check_boxes optional snippet_tags">
              <input type="hidden" name="snippet[tag_ids][]" value="">
              <div class="tag-item">
                <input class="form-check-input check_boxes optional tag-selector" type="checkbox" value="1" name="snippet[tag_ids][]" id="snippet_tag_ids_1">
                <label class="form-check-label collection_check_boxes pill-size" for="snippet_tag_ids_1">Too easy</label>
              </div>
              <div class="tag-item">
                <input class="form-check-input check_boxes optional tag-selector" type="checkbox" value="2" name="snippet[tag_ids][]" id="snippet_tag_ids_2">
                <label class="form-check-label collection_check_boxes pill-size" for="snippet_tag_ids_2">Just right</label>
              </div>
              <div class="tag-item">
                <input class="form-check-input check_boxes optional tag-selector" type="checkbox" value="3" name="snippet[tag_ids][]" id="snippet_tag_ids_3">
                <label class="form-check-label collection_check_boxes pill-size" for="snippet_tag_ids_3">Too difficult</label>
              </div>
            </fieldset>
            <p style='color: white; font-size: 24px;'>Length:</p>
            <fieldset class="form-group check_boxes optional snippet_tags">
              <input type="hidden" name="snippet[tag_ids][]" value="">
              <div class="tag-item">
                <input class="form-check-input check_boxes optional tag-selector" type="checkbox" value="1" name="snippet[tag_ids][]" id="snippet_tag_ids_4">
                <label class="form-check-label collection_check_boxes pill-size" for="snippet_tag_ids_4">Too short</label>
              </div>
              <div class="tag-item">
                <input class="form-check-input check_boxes optional tag-selector" type="checkbox" value="2" name="snippet[tag_ids][]" id="snippet_tag_ids_5">
                <label class="form-check-label collection_check_boxes pill-size" for="snippet_tag_ids_5">Just right</label>
              </div>
              <div class="tag-item">
                <input class="form-check-input check_boxes optional tag-selector" type="checkbox" value="3" name="snippet[tag_ids][]" id="snippet_tag_ids_6">
                <label class="form-check-label collection_check_boxes pill-size" for="snippet_tag_ids_6">Too long</label>
              </div>
            </fieldset>
            <div class='d-flex justify-content-around pt-3'>
            <%= link_to 'submit', home_path, style: 'color: #55A4BA' %>
            <%= link_to 'skip', home_path, style: 'color: #55A4BA' %>
          </div>
        </div>
      </div>
    </div>
    <%# <button data-action="click->routine-start#allowsound">
      <i class="fa-solid fa-headphones"></i>
    </button> %>
    <%# <%= audio_tag("https://cdn.pixabay.com/download/audio/2022/03/09/audio_97e49df2bd.mp3?filename=freezing-night-28066.mp3", autoplay: true, controls: true) %>
    <audio preload="auto" src="<%= asset_path("bell.wav") %>" class="d-none" data-routine-start-target="audio"></audio>
    <audio src="<%= asset_path("empty.mp3")  %>" data-routine-start-target="emptyAudio"></audio>
  </div>
  </div>
</div>

app/views/routines/show.html.erb
<div class='container'>
  <div class='routine-head'>
    <div class="d-flex justify-content-between">
      <h1><%= @routine.name %></h1>
      <% if @routine.imageable_type == "User"%>
        <%= link_to routine_path(@routine),method: :delete, data: { confirm: "Are you sure?" }, class: "delete-button" do%>
        <i class="fa-solid fa-trash"></i>
        <% end %>
      <% end %>
    </div>
    <%= @routine.description %>
    <div>
      <%= link_to 'start!', routine_routinestart_path(@routine), class:'btn btn-primary w-100' %>
    </div>
  </div>
 <div class='row'>
    <% @stretches.each do |s| %>
      <%= link_to stretch_path(s), class: 'col-6 card stretch-card' do %>
          <%= image_tag("#{s.photo}", class: "card-pic") %>
          <h4 class='text-center'><%= s.name %></h4>
      <% end %>
    <% end %>
</div>