config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'pages#landing'
  get 'home', to: 'pages#home'

  resources :sports, only: [:index, :show, :new, :create]
  resources :routines, only: [:new, :create, :show, :destroy] do
    get 'routinestart', to: 'routines#routine_start'
  end
  resources :stretches, only: [:index, :show] do
    resources :routines, only: :update
    resources :stretches_routines, only: :create
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/routine.rb
class Routine < ApplicationRecord
  belongs_to :imageable, polymorphic: true
  has_many :stretches_routines, dependent: :destroy
  has_many :stretches, through: :stretches_routines
  has_one_attached :background
end

app/models/sport.rb
class Sport < ApplicationRecord
  has_many :routines, as: :imageable
end

app/models/stretch.rb
class Stretch < ApplicationRecord
  has_many :stretches_routines
  has_many :routines, through: :stretches_routines
end

app/models/stretches_routine.rb
class StretchesRoutine < ApplicationRecord
  belongs_to :routine
  belongs_to :stretch
end

app/models/user.rb
class User < ApplicationRecord
  has_many :sports
  has_many :routines, as: :imageable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # def default_url_options
  #   { host: ENV["DOMAIN"] || "localhost:3000" }
  # end
end

app/controllers/routines_controller.rb
class RoutinesController < ApplicationController
  def show
    @routine = Routine.find(params[:id])
    @stretches = @routine.stretches
    @photos
  end

  def new
    @newroutine = Routine.new
  end

  def create
    @newroutine = Routine.new(routines_params)
    @newroutine.imageable = current_user
    if @newroutine.save
      redirect_to home_path
    else
      render :new
    end
  end

  def routine_start
    @routine = Routine.find(params[:routine_id])
    @stretches = @routine.stretches
  end

  def destroy
    @routine = Routine.find(params[:id])
    @routine.destroy

    redirect_to home_path
  end

  private

  def routines_params
    params.require(:routine).permit(:name, :description, :background)
  end
end

app/controllers/sports_controller.rb
class SportsController < ApplicationController
  def index
    @sports = Sport.where(imageable_type: 'Sport')
    @myroutines = Sport.where(imageable: current_user.id)
  end

  def show
    @sport = Sport.find(params[:id])
    @routines = Routine.where(imageable_type: 'Sport').where(imageable_id: @sport.id)
  end

  def new
    @myroutine = Sport.new
  end

  def create
    @myroutine = Sport.new(sports_params)
    @myroutine.user = current_user
    if @myroutine.save
      redirect_to root_path
    else
      render :new
    end
  end

  private

  def sports_params
    params.require(:sport).permit(:name)
  end
end

app/controllers/stretches_controller.rb
class StretchesController < ApplicationController
  def index
    # raise
    if params[:query].present?
      sql_query = " \
        stretches.name @@ :query \
        OR stretches.difficulty @@ :query \
      "
      @stretches = Stretch.where(sql_query, query: "%#{params[:query]}%")
    else
      @stretches = Stretch.all
    end
  end

  def show
    @stretch = Stretch.find(params[:id])
    @new = StretchesRoutine.new
  end
end

app/controllers/stretches_routines_controller.rb
class StretchesRoutinesController < ApplicationController
  def create
    if current_user.routines.any?
      routine = Routine.find(params[:stretches_routine][:routine])
      stretch = Stretch.find(params[:stretch_id])
      combo = StretchesRoutine.new
      combo.routine = routine
      combo.stretch = stretch
      combo.save
      redirect_to stretches_path
    else
      redirect_to new_routine_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/routines_helper.rb
module RoutinesHelper
end

app/helpers/sports_helper.rb
module SportsHelper
end

app/helpers/stretches_helper.rb
module StretchesHelper
end

app/helpers/stretchesroutines_helper.rb
module StretchesroutinesHelper
end

app/views/shared/_footer.html.erb
<div class="footer" <%= current_page?(root_path)  %>>
  <div class="foot-element">
    <a href="../home">
      <div class="icon"><i class="fa-solid fa-house"></i></div>
      <div class="foot-text"><p>home</p></div>
    </a>
  </div>
  <div class="foot-element">
    <a href="../stretches">
      <div class="icon"><i class="fa-solid fa-person-running"></i></div>
      <div class="foot-text"><p>stretches</p></div>
    </a>
  </div>
</div>

app/views/shared/_ios_pwa_links.html.erb
<link rel="apple-touch-icon" sizes="57x57" href="<%= image_path 'icons/apple-icon-57x57.png' %>">
<link rel="apple-touch-icon" sizes="60x60" href="<%= image_path 'icons/apple-icon-60x60.png' %>">
<link rel="apple-touch-icon" sizes="72x72" href="<%= image_path 'icons/apple-icon-72x72.png' %>">
<link rel="apple-touch-icon" sizes="76x76" href="<%= image_path 'icons/apple-icon-76x76.png' %>">
<link rel="apple-touch-icon" sizes="114x114" href="<%= image_path 'icons/apple-icon-114x114.png' %>">
<link rel="apple-touch-icon" sizes="120x120" href="<%= image_path 'icons/apple-icon-120x120.png' %>">
<link rel="apple-touch-icon" sizes="144x144" href="<%= image_path 'icons/apple-icon-144x144.png' %>">
<link rel="apple-touch-icon" sizes="152x152" href="<%= image_path 'icons/apple-icon-152x152.png' %>">
<link rel="apple-touch-icon" sizes="180x180" href="<%= image_path 'icons/apple-icon-180x180.png' %>">
<link rel="icon" type="image/png" sizes="32x32" href="<%= image_path 'icons/favicon-32x32.png' %>">
<link rel="icon" type="image/png" sizes="96x96" href="<%= image_path 'icons/favicon-96x96.png' %>">
<link rel="icon" type="image/png" sizes="16x16" href="<%= image_path 'icons/favicon-16x16.png' %>">

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-light navbar-expand-md py-3" <%= 'landnav' if current_page?(root_path) %> <%='nonav' if current_page?(routines_path) %> >
  <div class="container-fluid nav-2">
    <a class="navbar-brand d-flex align-items-center" href="/home">
      <span class="bs-icon-sm bs-icon-rounded bs-icon-primary d-flex justify-content-center align-items-center me-2 bs-icon" style="color: rgb(30, 54, 77);">
        <i class="icon fas fa-praying-hands"></i>
      </span>
    </a>
    <button class="navbar-toggler" data-bs-toggle="collapse" data-bs-target="#navcol-1">
      <span class="visually-hidden">Toggle navigation</span><span class="navbar-toggler-icon">
      </span>
    </button>
      <div id="navcol-1" class="collapse navbar-collapse">
        <ul class="navbar-nav" id= "log-sign">
          <% if user_signed_in? %>
            <li class="nav-item nav-link"><%= link_to "sign out", destroy_user_session_path, method: :delete, class: "nav-item nav-link" %>
          <% else %>
          <li class="nav-item nav-link"><%= link_to "sign up", new_user_registration_path %></li>
          <li class="nav-item nav-link"><%= link_to "log in", new_user_session_path %></li>
        </ul>
        </ul>
        <% end %>
      </div>
  </div>
</nav>

app/views/shared/_nofoot.html.erb
<div class="nofooter">
  <div class="nofoot-element">
    <%= link_to home_path do %>
      <div class="icon"><i class="fa-solid fa-house"></i></div>
    <% end %>
  </div>
  <div class="nofoot-element" data-controller="music">
    <a>
      <div class="icon">

      </div>
    </a>
  </div>
  <div class="nofoot-element">
    <a href="#">
      <div class="icon"><i class="fa-solid fa-arrow-rotate-left"></i></div>
    </a>
  </div>
</div>

app/views/shared/_nothing.html.erb
<div class="nothing"></div>