config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'pages#landing'
  get 'home', to: 'pages#home'

  resources :sports, only: [:index, :show, :new, :create]
  resources :routines, only: [:new, :create, :show, :destroy] do
    get 'routinestart', to: 'routines#routine_start'
  end
  resources :stretches, only: [:index, :show] do
    resources :routines, only: :update
    resources :stretches_routines, only: :create
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/routine.rb
class Routine < ApplicationRecord
  belongs_to :imageable, polymorphic: true
  has_many :stretches_routines, dependent: :destroy
  has_many :stretches, through: :stretches_routines
  has_one_attached :background
end

app/models/sport.rb
class Sport < ApplicationRecord
  has_many :routines, as: :imageable
end

app/models/stretch.rb
class Stretch < ApplicationRecord
  has_many :stretches_routines
  has_many :routines, through: :stretches_routines
end

app/models/stretches_routine.rb
class StretchesRoutine < ApplicationRecord
  belongs_to :routine
  belongs_to :stretch
end

app/models/user.rb
class User < ApplicationRecord
  has_many :sports
  has_many :routines, as: :imageable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # def default_url_options
  #   { host: ENV["DOMAIN"] || "localhost:3000" }
  # end
end

app/controllers/routines_controller.rb
class RoutinesController < ApplicationController
  def show
    @routine = Routine.find(params[:id])
    @stretches = @routine.stretches
    @photos
  end

  def new
    @newroutine = Routine.new
  end

  def create
    @newroutine = Routine.new(routines_params)
    @newroutine.imageable = current_user
    if @newroutine.save
      redirect_to home_path
    else
      render :new
    end
  end

  def routine_start
    @routine = Routine.find(params[:routine_id])
    @stretches = @routine.stretches
  end

  def destroy
    @routine = Routine.find(params[:id])
    @routine.destroy

    redirect_to home_path
  end

  private

  def routines_params
    params.require(:routine).permit(:name, :description, :background)
  end
end

app/controllers/sports_controller.rb
class SportsController < ApplicationController
  def index
    @sports = Sport.where(imageable_type: 'Sport')
    @myroutines = Sport.where(imageable: current_user.id)
  end

  def show
    @sport = Sport.find(params[:id])
    @routines = Routine.where(imageable_type: 'Sport').where(imageable_id: @sport.id)
  end

  def new
    @myroutine = Sport.new
  end

  def create
    @myroutine = Sport.new(sports_params)
    @myroutine.user = current_user
    if @myroutine.save
      redirect_to root_path
    else
      render :new
    end
  end

  private

  def sports_params
    params.require(:sport).permit(:name)
  end
end

app/controllers/stretches_controller.rb
class StretchesController < ApplicationController
  def index
    # raise
    if params[:query].present?
      sql_query = " \
        stretches.name @@ :query \
        OR stretches.difficulty @@ :query \
      "
      @stretches = Stretch.where(sql_query, query: "%#{params[:query]}%")
    else
      @stretches = Stretch.all
    end
  end

  def show
    @stretch = Stretch.find(params[:id])
    @new = StretchesRoutine.new
  end
end

app/controllers/stretches_routines_controller.rb
class StretchesRoutinesController < ApplicationController
  def create
    if current_user.routines.any?
      routine = Routine.find(params[:stretches_routine][:routine])
      stretch = Stretch.find(params[:stretch_id])
      combo = StretchesRoutine.new
      combo.routine = routine
      combo.stretch = stretch
      combo.save
      redirect_to stretches_path
    else
      redirect_to new_routine_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/routines_helper.rb
module RoutinesHelper
end

app/helpers/sports_helper.rb
module SportsHelper
end

app/helpers/stretches_helper.rb
module StretchesHelper
end

app/helpers/stretchesroutines_helper.rb
module StretchesroutinesHelper
end

app/views/pages/home.html.erb
<% if @myroutines %>
<div class='container'>
  <div class='header'>
    <h1>find the perfect routine <span style='color:white'>for you.</span></h1>
    <%# <p>*search bar goes here*</p> %>
  </div>
  <h3 style='color:#4B7395;font-size: 20;'>special sport routines</h3>
  <div class="owl-carousel" data-controller="home-carousel">
    <% @sports.each do |s| %>
      <%= link_to sport_path(s) do %>
        <div style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= image_path "sports/#{s.name}.jpg" %>)" class='sport-card card p-5'>
          <div class='card-text-routine'><%= s.name %></div>
        </div>
      <% end %>
    <% end %>
  </div>
  <h3 style='color:#4B7395;font-size: 20;'>my routines <%= link_to '+', new_routine_path, class:'btn btn-primary rounded-circle', style: 'font-size: 12px;' %></h3>
  <% if @myroutines %>
    <div id="myroutines-position" class="owl-carousel" data-controller="home-carousel">
      <% @myroutines.each do |s| %>
        <div>
          <%= link_to routine_path(s) do %>
            <%if s.background.attached?%>
              <div class='sport-card card p-5' style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path s.background.key %>')">
                <div class='card-text-routine'><%= s.name %></div>
              </div>
            <% else %>
              <div class='myroutines card p-5' style="background-image:linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= @photos.sample %>')">
                <div class='card-text-routine'><%= s.name %></div>
              </div>
            <% end %>
          <% end %>
        </div>
      <% end %>
    </div>
  <% end %>
  <%# <%= link_to 'yoga centers near me','#', class:'btn btn-primary' %>
</div>
<% end %>

app/views/pages/landing.html.erb
<% content_for :landing, render('shared/nothing') %>
<div class="bg-img">

  <%# <div class="text-container reveal fade-bottom">
    <div class="centered-title">welcometogasho.</div>
  </div> %>

  <section>
    <div class="centered-title container-landing">
    welcometogasho.
    <% if !user_signed_in? %>
      <div class="sign-up-links">
        <%= link_to "sign-up", new_user_registration_path %>
        <%= link_to "log in", new_user_session_path %>
      </div>
    <% end %>
    </div>
  </section>

  <section id="sports">
    <div class="container-landing reveal">
      <h2>sports</h2>
      <div class="text-container">
        <div class="text-box">
          <h3>football</h3>
          <p>
            Your glutes, quadriceps and hamstrings provide the force behind many football movements, and they often work together. Your glutes, located in your buttocks, along with your hamstrings, drive your legs back behind you. Your quadriceps, a collection of four muscles at the fronts of your thighs, extend your knees.
          </p>
        </div>
        <div class="text-box">
          <h3>basketball</h3>
          <p>
            The shoulder, chest, biceps and triceps are all muscle areas that basketball players use during play. The triceps are a critical muscle when shooting long-range baskets such as three-pointers. Building triceps muscles helps players who shoot well from close distances but struggle with deep shooting.
          </p>
        </div>
        <div class="text-box">
          <h3>tennis</h3>
          <p>
            It all starts from the ground when your feet push off the court to move towards the ball. Then, this energy created by this first event is successively transferred into other parts of your body. The energy goes from your lower-body muscles to your core, and then to your upper body muscles. And finally, the energy travels from your hand to the racquet and then to the ball.
          </p>
        </div>
      </div>
    </div>
  </section>

  <section id="routines">
    <div class="container-landing reveal">
      <h2>routines</h2>
      <div class="text-container">
        <div class="text-box">
          <h3>football stretch routine</h3>
          <p>
            We recommend stretching the following areas for football-related stretching.
              Hip flexors
              Front thigh
              Rear thigh
              Calf
              Inner thigh
              Glutes
              Outer thigh
          </p>
        </div>
        <div class="text-box">
          <h3>basketball stretch routine</h3>
          <p>
            We recommend the following stretches for basketball-related stretching.
              Ankle rolls
              Walking lunges
              Squats
              Lateral hip swings
              Walking quadricep stretch
              Walking knee hugs
              Karaoke
          </p>
        </div>
        <div class="text-box">
          <h3>tennis stretch routine</h3>
          <p>
            We recommend the following stretches for basketball-related stretching.
              Standing quadriceps stretch
              Simple hamstring stretch
              Low lunge twist
              Cross body shoulder
              Towel calf
              Anterior shoulder
              Tennis elbow stretch
          </p>
        </div>
      </div>
    </div>
  </section>

  <section id="stretches">
    <div class="container-landing reveal">
      <h2>stretches</h2>
      <div class="text-container">
        <div class="text-box">
          <h3>extended side angle</h3>
          <img src="https://pocketyoga.com/assets/images/full/warrior_ii_forward_arm_forward_L.png" alt="" widht="200px" height="300px">
        </div>
        <div class="text-box">
          <h3>butterfly</h3>
          <img src="https://pocketyoga.com/assets/images/full/butterfly.png" alt="" widht="200px" height="300px">
        </div>
        <div class="text-box">
          <h3>wide splits</h3>
          <img src="https://pocketyoga.com/assets/images/full/splits_wide.png" alt="" widht="200px" height="300px">
        </div>
      </div>
    </div>
  </section>
</div>

app/views/pages/routinestart.html.erb
<div id="carouselExampleSlidesOnly" class="vertical carousel slide" data-bs-ride="carousel" data-interval="10000">
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img src=<%= stretch.photo %> class="d-block w-100" alt="...">
    </div>
  <% @stretches.each do |stretch| %>
    <div class="carousel-item">
      <img src=<%= stretch.photo %> class="d-block w-100" alt="...">
      <h1><%= stretch.name %></h1>
    </div>
  <% end %>
  </div>
</div>